create table if not exists institutes
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name  VARCHAR(255)                             NOT NULL,
    short_name VARCHAR(255)                             NOT NULL,
    address    VARCHAR(255)                             NOT NULL,
    PRIMARY KEY (id),
    unique (id),
    unique (short_name)
);

create table if not exists courses
(
    id                UUID         NOT NULL,
    course_name       VARCHAR(255) NOT NULL,
    institute_name    VARCHAR(255),
    institute_address VARCHAR(255) NOT NULL,
    professors        TEXT         NOT NULL,
    create_timestamp  timestamptz  NOT NULL,
    PRIMARY KEY (id),
    unique (id)
);
create index if not exists idx_courses_professors on courses (professors);
create index if not exists idx_courses_institute on courses (institute_name);

create table if not exists class_sessions
(
    id                UUID                        NOT NULL,
    status            VARCHAR(255)                NOT NULL,
    session_name      VARCHAR(255)                NOT NULL,
    course_id         UUID                        NOT NULL,
    course_name       VARCHAR(255)                NOT NULL,
    professors        VARCHAR(255)                NOT NULL,
    institute_name    VARCHAR(255),
    institute_address VARCHAR(255)                NOT NULL,
    start_date_time   timestamp WITHOUT TIME ZONE NOT NULL,
    end_date_time     timestamp WITHOUT TIME ZONE NOT NULL,
    room_name         VARCHAR(255),
    professor_name    VARCHAR(255)                NOT NULL,
    disable_timestamp timestamptz,
    create_timestamp  timestamptz                 NOT NULL,
    primary key (id),
    CONSTRAINT fk_class_sessions foreign key (course_id) references courses (id) on update cascade
);
create index if not exists idx_sessions_course_id on class_sessions (course_id);
create index if not exists idx_sessions_course_name on class_sessions (course_name);
create index if not exists idx_sessions_professors on class_sessions (professors);
create index if not exists idx_sessions_professor_name on class_sessions (professor_name);

create table if not exists professors
(
    id        UUID DEFAULT gen_random_uuid() NOT NULL,
    username  VARCHAR(255)                   NOT NULL,
    full_name VARCHAR(255)                   NOT NULL,
    PRIMARY KEY (id),
    unique (id),
    CONSTRAINT fk_professors foreign key (username) references users (username) on delete cascade
);
create unique index if not exists udx_professors_username on professors (username);
create index if not exists udx_professors_name on professors (full_name);

create table if not exists reviews
(
    id                UUID DEFAULT gen_random_uuid() NOT NULL,
    session_id        UUID                           NOT NULL,
    student_full_name VARCHAR(255)                   NOT NULL,
    review_value      SMALLINT                       NOT NULL,
    review_comment    VARCHAR(255),
    review_timestamp  timestamptz                    NOT NULL,
    primary key (id),
    unique (id),
    CONSTRAINT fk_reviews foreign key (session_id) references class_sessions (id) on delete cascade
);
create index if not exists idx_reviews_session_id on reviews (session_id);

